version: '3'

networks:
  automation_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  selenium:
    image: selenium/standalone-chrome
    networks:
      - automation_net
    ports:
      - 4444:4444
    restart: always

  crawler:
    build:
      context: ./crawler
    volumes:
     - ./crawler:/crawler
    command: sh -c "python3 runner.py"
    networks:
      - automation_net
    depends_on:
      - selenium
  lb:
    image: haproxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./haproxy/prod:/usr/local/etc/haproxy
    networks:
      - automation_net
    restart: on-failure
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/metrics']
      interval: 30s
      timeout: 30s
      retries: 3
  server:
    image: '${SERVER_API_DOCKER_TAG:-api-dev:latest}'
    build:
      context: ./server
      target: release
    command: yarn start
    env_file:
      - ./server/.env
    environment:
      LOAD_ENV: 'true'
      APPID: 1111
    ports:
      - '1111:1111'
    networks:
      - automation_net
    restart: on-failure
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/status']
      interval: 30s
      timeout: 30s
      retries: 3
